### ISSUE TITLE
Alert by github notification system in case of failure

### ISSUE THREAD

**Issue by NotesOfReality** [tooruu/HoYoDaily#1]
I changed my hoYoLab account password, which changed the LTUID and LTOKEN values and prevented the workflow from success.
Here's the log of what happened https://github.com/NotesOfReality/HoYoDaily/runs/4192019016?check_suite_focus=true#step:2:6 , be it clear I only play HI3 and the workflow (obviously?) only needed the updated LTUID and LTOKEN values to work well again.

Could GH workflow be instructed so that it sends a notification in case of failure or even just in case of `Response: Please log in to take part in the event`  ?

**Comment by tooruu** [comment]
LTUID is your HoYoLAB user account ID, it never changes. You only need your new LTOKEN.
As for notifications, I'll look into implementing this. I just learned that GitHub has a notification system so I need to work out how to use it. Thank you for the suggestion!

**Comment by NotesOfReality** [comment]
I see, thanks for the clarification and thanks for your willingness! ❤️

**Comment by tooruu** [comment]
It appears that it's not possible to send notifications from within workflows.
All I can do is add a warning to [README.md](../blob/master/README.md) that changing HoYoLAB password regenerates your token.

**Comment by NotesOfReality** [comment]
Oh well, thanks for looking into it nonetheless! ❤️ 
The best I can do is providing you an _incredibly valuable and complex_ [README.md commit I did long ago about the password change "eventual issue"](https://github.com/NotesOfReality/HoYoDaily/commit/7765590c77e0e7488d791fd2e2a68660ec4fa6fb), which is really really little but it's honest work 😆.

**Comment by tooruu** [comment]
Added warning about password change in https://github.com/tooruu/HoYoDaily/commit/25aec4383d1e89a5420918f7ee1a0167a1a76003.
