### ISSUE TITLE
Specific way to write LTUID and LTOKEN key?

### ISSUE THREAD

**Issue by farsdewibs0n** [tooruu/HoYoDaily#2]
Is there a way to write the LTUID and LTOKEN on Secrets? Because I seem unable to claim it, Or is it because I already claimed it? Seems that it doesn't read my LTUID and LTOKEN at all (says that I have't logged in).
Log:
[logs_5.zip](https://github.com/tooruu/HoYoDaily/files/8864862/logs_5.zip)

**Comment by tooruu** [comment]
You need to go to your repo's [Secrets](https://github.com/farsdewibs0n/HoYoDaily/settings/secrets/actions) and add LTUID and LTOKEN as described in the readme.

**Comment by tooruu** [comment]
You need to create 2 secrets. One named **LTUID** and ther other one **LTOKEN**, and set their values accordingly.

**Comment by farsdewibs0n** [comment]
![image](https://user-images.githubusercontent.com/13050356/173732387-8c5ba262-d8e9-47fe-8ade-3ef8124f304d.png)
Thanks it works now.
I'd suggest adding "make 2 secets" step on How to Use.

Closing this issue.
